# Generated by Django 4.2.4 on 2023-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medstore', '0002_remove_employee_e_id_alter_customer_phn_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='stock',
            new_name='mrp',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='mname',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(),
        ),
    ]
