# Generated by Django 4.2.4 on 2023-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medstore', '0003_rename_stock_medicine_mrp_remove_medicine_mname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='mrp',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
