# Generated by Django 4.2.4 on 2023-09-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medstore', '0004_remove_medicine_mrp_alter_medicine_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='m_id',
        ),
        migrations.AddField(
            model_name='medicine',
            name='mrp',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(),
        ),
    ]
