# Generated by Django 4.2.4 on 2023-09-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medstore', '0005_remove_medicine_m_id_medicine_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='m_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
